// livro-clientes/livros-react/src/LivroDados.js
import React, {useState} from "react";
import ControleLivros from "./controle/ControleLivros";
import ControleEditora from "./controle/ControleEditora";
import { useNavigate } from "react-router-dom";

const controleLivros = new ControleLivros();
const controleEditora = new ControleEditora();

const LivroDados = props => {
    const opcoes = controleEditora.getEditoras();
    const [titulo, setTitulo] = useState("");
    const [resumo, setResumo] = useState("");
    const [autores, setAutores] = useState("");
    const [codEditora, setCodEditora] = useState(opcoes[0].codEditora);
    const navigate = useNavigate();

    const tratarCombo = (event) => {
        setCodEditora(Number(event.target.value));
    };

    const incluir = (event) => {
        event.preventDefault();
        const livro = {
            codigo: "",
            codEditora: codEditora,
            titulo: titulo,
            resumo: resumo,
            autores: autores.split("\n")
        };
        controleLivros.incluir(livro)
            .then(_ => navigate("/"));
    };

    return (
        <main>
            <h2>Dados do Livro</h2>
            <form onSubmit={incluir}>
                <div className="form-group" >
                    <label htmlFor="titulo">Título</label>
                    <input id="titulo" className="form-control" type="text" value={titulo} onChange={(e) => setTitulo(e.target.value)} />
                </div>
                <div>
                    <label htmlFor="resumo">Resumo</label>
                    <textarea id="resumo" className="form-control" value={resumo} onChange={(e) => setResumo(e.target.value)} />
                </div>
                <div>
                    <label htmlFor="editora">Editora</label>
                    <select id="editora" className="form-control" value={codEditora} onChange={tratarCombo}>
                        {opcoes.map((item) => (
                            <option key={item.codEditora} value={item.codEditora}>
                                {item.nome}
                            </option>
                        ))}
                    </select>
                </div>
                <div>
                    <label htmlFor="autores">Autores (1 por linha)</label>
                    <textarea id="autores" className="form-control" value={autores} onChange={(e) => setAutores(e.target.value)} />
                </div>
                <br></br>
                <button className="btn btn-primary" type="submit">Salvar Dados</button>
            </form>
        </main>
    )
}
export default LivroDados;

// livro-clientes/livros-angular/src/app/livro-dados/livro-dados.component.ts
import { Component, OnInit } from '@angular/core';
import { ActivatedRoute, Router } from '@angular/router';
import { ControleEditoraService } from '../controle-editora.service';
import { ControleLivrosService } from '../controle-livros.service';
import { Livro } from '../livro';
import { Editora } from '../editora';

@Component({
  selector: 'app-livro-dados',
  templateUrl: './livro-dados.component.html',
  styleUrls: ['./livro-dados.component.css'],
})
export class LivroDadosComponent implements OnInit {
  livro: Livro;
  autoresForm: string = '';
  editoras: Array<Editora> = [];
  editoraSelecionada: Editora | null = null;

  constructor(
    private servEditora: ControleEditoraService,
    private servLivros: ControleLivrosService,
    private router: Router
  ) {
    this.livro = new Livro('','',0, '', []);
  }

  ngOnInit() {
    this.editoras = this.servEditora.getEditoras();
  }

  incluir(): void {
    // Chame o método incluir do controlador
    this.servLivros.incluir(this.livro)
      .then(() => {
        // Ao término da execução do método incluir, navegue para "/lista"
        this.router.navigateByUrl('/lista');
      });
  }
}

<main class="container">
  <h2>Livros</h2>

  <form (submit)="incluir()" ngNativeValidate>
    <div class="form-group">
      <label for="titulo">Título:</label>
      <input type="text" id="titulo" name="titulo" class="form-control" required [(ngModel)]="livro.titulo">
    </div>

    <div class="form-group">
      <label for="resumo">Resumo:</label>
      <textarea id="resumo" name="resumo" class="form-control" required [(ngModel)]="livro.resumo"></textarea>
    </div>

    <div class="form-group">
      <label for="editora">Editora:</label>
      <select id="editora" name="editora" class="form-control" required- [(ngModel)]="editoraSelecionada">
        <option *ngFor="let editora of editoras" [ngValue]="editora">{{ editora.nome }}</option>
      </select>
    </div>

    <div class="form-group">
      <label for="autores">Autores:</label>
      <textarea id="autores" name="autores" class="form-control" [(ngModel)]="autoresForm"></textarea>
    </div>

    <button type="submit" class="btn btn-primary">Salvar</button>
  </form>
</main>
