// livro-clientes/livros-angular/src/app/livro-lista/livro-lista.component.ts
import { Component, OnInit } from '@angular/core';
import { Livro } from '../livro';
import { Editora } from '../editora';
import { ControleEditoraService } from '../controle-editora.service';
import { ControleLivrosService } from '../controle-livros.service';

@Component({
  selector: 'app-livro-lista',
  templateUrl: './livro-lista.component.html',
  styleUrls: ['./livro-lista.component.css']
})
export class LivroListaComponent implements OnInit {
  livros: Livro[] = [];

  constructor(private controleLivrosService: ControleLivrosService) {}

  ngOnInit(): void {
    // Alterar a implementação do método ngOnInit
    this.controleLivrosService.obterLivros().then(livros => {
      this.livros = livros;
    });
  }

  // Alterar a assinatura do método excluir
  excluir(codigo: string | null): void {
    this.controleLivrosService.excluir(codigo)
      .then(() => {
        // Ao final da execução de excluir, chame obterLivros novamente
        return this.controleLivrosService.obterLivros();
      })
      .then(livros => {
        this.livros = livros;
      });
  }
}

<main class="container mt-4">
  <h1>Livros</h1>
  <table class="table table-striped">
    <thead class="head-tabela">
      <tr>
        <th>Título</th>
        <th>Resumo</th>
        <th>Editora</th>
        <th>Autores</th>
      </tr>
    </thead>
    <tbody class="tabela">
      <tr *ngFor="let livro of livros">
        <td>
          {{ livro.titulo }} <br />
          <button class="btn btn-danger btn-sm" (click)="excluir(livro.codigo)">
            Excluir
          </button>
        </td>
        <td>{{ livro.resumo }}</td>
        <td>{{ livro.codEditora }}</td>
        <td>
          <ul>
            <li *ngFor="let autor of livro.autores">{{ autor }}</li>
          </ul>
        </td>
      </tr>
    </tbody>
  </table>
</main>

// livro-clientes/livros-react/src/LivroLista.js
/* eslint-disable jsx-a11y/scope */
import React, {useState, useEffect} from "react";
import ControleLivros from "./controle/ControleLivros";
import ControleEditora from "./controle/ControleEditora";

const controleLivros = new ControleLivros();
const controleEditora = new ControleEditora();

const LinhaLivro = props => {
    const { livro, excluir } = props;
    const nomeEditora = controleEditora.getNomeEditora;

    return (
        <tr>
            <td>
                <p>{livro.titulo}</p>
                <button className="btn btn-danger pull-right" onClick={() => excluir(livro.codigo)}>Excluir</button>
            </td>
            <td>{livro.resumo}</td>
            <td>{nomeEditora(livro.codEditora)}</td>
            <td>
                <ul>
                {livro.autores.map((autor, index) => (
                    <li key={index}>{autor}</li>
                ))}
                </ul>
            </td>
        </tr>
    );
}

const LivroLista = () => {
    const [livros, setLivros] = useState([]);
    const [carregado, setCarregado] = useState(false);

    useEffect(() => {
        controleLivros.obterLivros()
            .then(livros => setLivros(livros))
            .then(() => setCarregado(true));
    }, [carregado]);

    const excluir = (codigo) => {
        controleLivros.excluir(codigo)
            .then(() => setCarregado(false));
    }

    return (
        <main class="container">
            <h1>Catálogo de Livros</h1>
            <table className="table table-hover">
                <thead className="table-dark">
                    <tr scope="row">
                        <th>Título</th>
                        <th>Resumo</th>
                        <th>Editora</th>
                        <th>Autores</th>
                    </tr>
                </thead>
                <tbody>
                {livros.map((livro, index) => (
                    <LinhaLivro
                        key={index}
                        livro={livro}
                        excluir={excluir}
                        getNomeEditora={controleEditora.getNomeEditora}
                    />
                ))}
                </tbody>
            </table>
        </main>
    )
}

export default LivroLista;
